services:
  
  meu-app-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-tcc-app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      db-postgres:
        condition: service_healthy
  
  db-postgres:
    image: postgres:14
    container_name: meu-tcc-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=meutccdb
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meutccdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu-tcc-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-postgres

volumes:
  postgres-data: 