services:
  
  meu-app-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu-tcc-app
    ports:
      - "8080:8080" 
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      # Configuração para aceitar o certificado de desenvolvimento do Docker
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mysecretpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https/:ro 
    depends_on:
      - db-postgres 

  
  db-postgres:
    image: postgres:15 
    container_name: meu-tcc-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=meutccdb
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu-tcc-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db-postgres

volumes:
  postgres-data: 