// <auto-generated />
using MeuTccMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeuTccMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeuTccMvc.Models.ItemMidia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("integer");

                    b.Property<string>("AutorDiretor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Genero")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sinopse")
                        .HasColumnType("text");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ItensMidia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLancamento = 1954,
                            AutorDiretor = "J.R.R. Tolkien",
                            Genero = "Fantasia",
                            Sinopse = "Um jovem hobbit herda um anel mágico e perigoso que deve ser destruído antes que caia nas mãos do mal.",
                            TipoMidia = "Livro",
                            Titulo = "O Senhor dos Anéis: A Sociedade do Anel"
                        },
                        new
                        {
                            Id = 2,
                            AnoLancamento = 1965,
                            AutorDiretor = "Frank Herbert",
                            Genero = "Ficção Científica",
                            Sinopse = "A jornada de um jovem nobre em um planeta desértico perigoso para garantir o futuro de seu povo.",
                            TipoMidia = "Livro",
                            Titulo = "Duna"
                        },
                        new
                        {
                            Id = 3,
                            AnoLancamento = 1972,
                            AutorDiretor = "Francis Ford Coppola",
                            Genero = "Crime, Drama",
                            Sinopse = "O patriarca de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.",
                            TipoMidia = "Filme",
                            Titulo = "O Poderoso Chefão"
                        },
                        new
                        {
                            Id = 4,
                            AnoLancamento = 2014,
                            AutorDiretor = "Christopher Nolan",
                            Genero = "Ficção Científica, Aventura",
                            Sinopse = "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço na tentativa de garantir a sobrevivência da humanidade.",
                            TipoMidia = "Filme",
                            Titulo = "Interestelar"
                        },
                        new
                        {
                            Id = 5,
                            AnoLancamento = 2008,
                            AutorDiretor = "Vince Gilligan",
                            Genero = "Crime, Drama, Suspense",
                            Sinopse = "Um professor de química do ensino médio diagnosticado com câncer de pulmão inoperável passa a produzir e vender metanfetamina para garantir o futuro de sua família.",
                            TipoMidia = "Serie",
                            Titulo = "Breaking Bad"
                        },
                        new
                        {
                            Id = 6,
                            AnoLancamento = 2005,
                            AutorDiretor = "Greg Daniels",
                            Genero = "Comédia",
                            Sinopse = "Um documentário sobre o dia a dia cômico e, por vezes, tocante dos funcionários de uma empresa de papel.",
                            TipoMidia = "Serie",
                            Titulo = "The Office (US)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
